// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: path_acl.sql

package postgres

import (
	"context"
)

const deleteACL = `-- name: DeleteACL :exec
DELETE FROM path_acl
WHERE path = $1 AND principal_type = $2 AND principal_id = $3
`

func (q *Queries) DeleteACL(ctx context.Context, arg DeleteACLParams) error {
	_, err := q.db.Exec(ctx, deleteACL, arg.Path, arg.PrincipalType, arg.PrincipalID)
	return err
}

const deleteACLForPath = `-- name: DeleteACLForPath :exec
DELETE FROM path_acl WHERE path = $1
`

func (q *Queries) DeleteACLForPath(ctx context.Context, path string) error {
	_, err := q.db.Exec(ctx, deleteACLForPath, path)
	return err
}

const deleteACLForPrincipal = `-- name: DeleteACLForPrincipal :exec
DELETE FROM path_acl
WHERE principal_type = $1 AND principal_id = $2
`

func (q *Queries) DeleteACLForPrincipal(ctx context.Context, arg DeleteACLForPrincipalParams) error {
	_, err := q.db.Exec(ctx, deleteACLForPrincipal, arg.PrincipalType, arg.PrincipalID)
	return err
}

const listACLByPath = `-- name: ListACLByPath :many
SELECT path, principal_type, principal_id, allow, deny FROM path_acl WHERE path = $1 ORDER BY principal_type, principal_id
`

func (q *Queries) ListACLByPath(ctx context.Context, path string) ([]PathAcl, error) {
	rows, err := q.db.Query(ctx, listACLByPath, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PathAcl{}
	for rows.Next() {
		var i PathAcl
		if err := rows.Scan(
			&i.Path,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listACLByPaths = `-- name: ListACLByPaths :many
SELECT path, principal_type, principal_id, allow, deny FROM path_acl
WHERE path = ANY($1::text[])
ORDER BY path, principal_type, principal_id
`

func (q *Queries) ListACLByPaths(ctx context.Context, paths []string) ([]PathAcl, error) {
	rows, err := q.db.Query(ctx, listACLByPaths, paths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PathAcl{}
	for rows.Next() {
		var i PathAcl
		if err := rows.Scan(
			&i.Path,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listACLUnder = `-- name: ListACLUnder :many
SELECT path, principal_type, principal_id, allow, deny FROM path_acl
WHERE path = $1 OR path LIKE $2
ORDER BY path, principal_type, principal_id
`

func (q *Queries) ListACLUnder(ctx context.Context, arg ListACLUnderParams) ([]PathAcl, error) {
	rows, err := q.db.Query(ctx, listACLUnder, arg.Path, arg.PathLike)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PathAcl{}
	for rows.Next() {
		var i PathAcl
		if err := rows.Scan(
			&i.Path,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllACL = `-- name: ListAllACL :many
SELECT path, principal_type, principal_id, allow, deny FROM path_acl ORDER BY path, principal_type, principal_id
`

func (q *Queries) ListAllACL(ctx context.Context) ([]PathAcl, error) {
	rows, err := q.db.Query(ctx, listAllACL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PathAcl{}
	for rows.Next() {
		var i PathAcl
		if err := rows.Scan(
			&i.Path,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertACL = `-- name: UpsertACL :one
INSERT INTO path_acl (path, principal_type, principal_id, allow, deny)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (path, principal_type, principal_id) DO UPDATE SET
    allow = excluded.allow,
    deny = excluded.deny
RETURNING path, principal_type, principal_id, allow, deny
`

func (q *Queries) UpsertACL(ctx context.Context, arg UpsertACLParams) (PathAcl, error) {
	row := q.db.QueryRow(ctx, upsertACL,
		arg.Path,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Allow,
		arg.Deny,
	)
	var i PathAcl
	err := row.Scan(
		&i.Path,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Allow,
		&i.Deny,
	)
	return i, err
}
