// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package postgres

import (
	"context"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (token_hash, token_prefix, user_id, description, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING token_hash, token_prefix, user_id, description, created_at
`

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.UserID,
		arg.Description,
		arg.CreatedAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.TokenHash,
		&i.TokenPrefix,
		&i.UserID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE token_hash = $1 AND user_id = $2
`

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, arg.TokenHash, arg.UserID)
	return err
}

const deleteAPITokensForUser = `-- name: DeleteAPITokensForUser :exec
DELETE FROM api_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAPITokensForUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAPITokensForUser, userID)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT token_hash, token_prefix, user_id, description, created_at FROM api_tokens WHERE token_hash = $1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.TokenHash,
		&i.TokenPrefix,
		&i.UserID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT token_hash, token_prefix, user_id, description, created_at FROM api_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPITokensByUser(ctx context.Context, userID string) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.TokenHash,
			&i.TokenPrefix,
			&i.UserID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
