// Code generated by tools/gen_db_bridge.go; DO NOT EDIT.

package sqlite

import "github.com/topi314/godrive/server/database/dbtypes"

type DeleteFilesUnderParams = dbtypes.DeleteFilesUnderParams
type ListFilesUnderParams = dbtypes.ListFilesUnderParams
type UpdateFileMetaParams = dbtypes.UpdateFileMetaParams
type UpdateFileOwnerParams = dbtypes.UpdateFileOwnerParams
type UpdateFilesOwnerUnderParams = dbtypes.UpdateFilesOwnerUnderParams
type UpsertFileParams = dbtypes.UpsertFileParams
type ApiToken = dbtypes.ApiToken
type File = dbtypes.File
type PathAcl = dbtypes.PathAcl
type Session = dbtypes.Session
type Share = dbtypes.Share
type UploadSession = dbtypes.UploadSession
type User = dbtypes.User
type DeleteACLParams = dbtypes.DeleteACLParams
type DeleteACLForPrincipalParams = dbtypes.DeleteACLForPrincipalParams
type ListACLUnderParams = dbtypes.ListACLUnderParams
type UpsertACLParams = dbtypes.UpsertACLParams
type UpsertSessionParams = dbtypes.UpsertSessionParams
type CreateShareParams = dbtypes.CreateShareParams
type ListSharesByPathParams = dbtypes.ListSharesByPathParams
type UpdateSharePathParams = dbtypes.UpdateSharePathParams
type CreateAPITokenParams = dbtypes.CreateAPITokenParams
type DeleteAPITokenParams = dbtypes.DeleteAPITokenParams
type CountActiveUploadSessionsByShareParams = dbtypes.CountActiveUploadSessionsByShareParams
type CountActiveUploadSessionsByUserParams = dbtypes.CountActiveUploadSessionsByUserParams
type CreateUploadSessionParams = dbtypes.CreateUploadSessionParams
type UpdateUploadSessionOffsetParams = dbtypes.UpdateUploadSessionOffsetParams
type UpdateUserHomeParams = dbtypes.UpdateUserHomeParams
type UpsertUserParams = dbtypes.UpsertUserParams
