// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlite

import (
	"context"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = ?1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForUser, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, access_token, expiry, refresh_token, id_token, created_at, updated_at FROM sessions WHERE id = ?1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.Expiry,
		&i.RefreshToken,
		&i.IDToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO sessions (id, user_id, access_token, expiry, refresh_token, id_token, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
ON CONFLICT (id) DO UPDATE SET
    user_id = excluded.user_id,
    access_token = excluded.access_token,
    expiry = excluded.expiry,
    refresh_token = excluded.refresh_token,
    id_token = excluded.id_token,
    updated_at = excluded.updated_at
RETURNING id, user_id, access_token, expiry, refresh_token, id_token, created_at, updated_at
`

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, upsertSession,
		arg.ID,
		arg.UserID,
		arg.AccessToken,
		arg.Expiry,
		arg.RefreshToken,
		arg.IDToken,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.Expiry,
		&i.RefreshToken,
		&i.IDToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
