// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package sqlite

import (
	"context"
)

const createShare = `-- name: CreateShare :one
INSERT INTO shares (id, path, user_id, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, path, user_id, created_at, expires_at
`

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, createShare,
		arg.ID,
		arg.Path,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteShare = `-- name: DeleteShare :exec
DELETE FROM shares WHERE id = ?1
`

func (q *Queries) DeleteShare(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteShare, id)
	return err
}

const deleteSharesForPath = `-- name: DeleteSharesForPath :exec
DELETE FROM shares WHERE path = ?1
`

func (q *Queries) DeleteSharesForPath(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteSharesForPath, path)
	return err
}

const getShare = `-- name: GetShare :one
SELECT id, path, user_id, created_at, expires_at FROM shares WHERE id = ?1
`

func (q *Queries) GetShare(ctx context.Context, id string) (Share, error) {
	row := q.db.QueryRowContext(ctx, getShare, id)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listSharesByPath = `-- name: ListSharesByPath :many
SELECT id, path, user_id, created_at, expires_at FROM shares WHERE path = ?1 OR path LIKE ?2 ORDER BY created_at DESC
`

func (q *Queries) ListSharesByPath(ctx context.Context, arg ListSharesByPathParams) ([]Share, error) {
	rows, err := q.db.QueryContext(ctx, listSharesByPath, arg.Path, arg.PathLike)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Share{}
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesByUser = `-- name: ListSharesByUser :many
SELECT id, path, user_id, created_at, expires_at FROM shares WHERE user_id = ?1 ORDER BY created_at DESC
`

func (q *Queries) ListSharesByUser(ctx context.Context, userID string) ([]Share, error) {
	rows, err := q.db.QueryContext(ctx, listSharesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Share{}
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSharePath = `-- name: UpdateSharePath :exec
UPDATE shares SET path = ?1 WHERE id = ?2
`

func (q *Queries) UpdateSharePath(ctx context.Context, arg UpdateSharePathParams) error {
	_, err := q.db.ExecContext(ctx, updateSharePath, arg.Path, arg.ID)
	return err
}
