// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sqlite

import (
	"context"
)

const countActiveUploadSessionsByShare = `-- name: CountActiveUploadSessionsByShare :one
SELECT COUNT(*) FROM upload_sessions
WHERE share_id = ?1
  AND expires_at > ?2
`

func (q *Queries) CountActiveUploadSessionsByShare(ctx context.Context, arg CountActiveUploadSessionsByShareParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUploadSessionsByShare, arg.ShareID, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveUploadSessionsByUser = `-- name: CountActiveUploadSessionsByUser :one
SELECT COUNT(*) FROM upload_sessions
WHERE user_id = ?1
  AND expires_at > ?2
  AND (share_id IS NULL OR share_id = '')
`

func (q *Queries) CountActiveUploadSessionsByUser(ctx context.Context, arg CountActiveUploadSessionsByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUploadSessionsByUser, arg.UserID, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUploadSession = `-- name: CreateUploadSession :one
INSERT INTO upload_sessions (
    id, user_id, share_id, path, size, content_type, description, upload_offset, replace_file,
    temp_key, s3_upload_id, s3_parts, expires_at, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9,
    ?10, ?11, ?12, ?13, ?14, ?15
)
RETURNING id, user_id, share_id, path, size, content_type, description, upload_offset, replace_file, temp_key, s3_upload_id, s3_parts, expires_at, created_at, updated_at
`

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, createUploadSession,
		arg.ID,
		arg.UserID,
		arg.ShareID,
		arg.Path,
		arg.Size,
		arg.ContentType,
		arg.Description,
		arg.UploadOffset,
		arg.ReplaceFile,
		arg.TempKey,
		arg.S3UploadID,
		arg.S3Parts,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShareID,
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.Description,
		&i.UploadOffset,
		&i.ReplaceFile,
		&i.TempKey,
		&i.S3UploadID,
		&i.S3Parts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredUploadSessions = `-- name: DeleteExpiredUploadSessions :many
DELETE FROM upload_sessions
WHERE expires_at < datetime('now')
RETURNING id, user_id, share_id, path, size, content_type, description, upload_offset, replace_file, temp_key, s3_upload_id, s3_parts, expires_at, created_at, updated_at
`

func (q *Queries) DeleteExpiredUploadSessions(ctx context.Context) ([]UploadSession, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredUploadSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadSession{}
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShareID,
			&i.Path,
			&i.Size,
			&i.ContentType,
			&i.Description,
			&i.UploadOffset,
			&i.ReplaceFile,
			&i.TempKey,
			&i.S3UploadID,
			&i.S3Parts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUploadSession = `-- name: DeleteUploadSession :exec
DELETE FROM upload_sessions WHERE id = ?1
`

func (q *Queries) DeleteUploadSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUploadSession, id)
	return err
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT id, user_id, share_id, path, size, content_type, description, upload_offset, replace_file, temp_key, s3_upload_id, s3_parts, expires_at, created_at, updated_at FROM upload_sessions WHERE id = ?1
`

func (q *Queries) GetUploadSession(ctx context.Context, id string) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, getUploadSession, id)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShareID,
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.Description,
		&i.UploadOffset,
		&i.ReplaceFile,
		&i.TempKey,
		&i.S3UploadID,
		&i.S3Parts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUploadSessionOffset = `-- name: UpdateUploadSessionOffset :one
UPDATE upload_sessions
SET upload_offset = ?1,
    s3_parts = ?2,
    updated_at = ?3
WHERE id = ?4
RETURNING id, user_id, share_id, path, size, content_type, description, upload_offset, replace_file, temp_key, s3_upload_id, s3_parts, expires_at, created_at, updated_at
`

func (q *Queries) UpdateUploadSessionOffset(ctx context.Context, arg UpdateUploadSessionOffsetParams) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, updateUploadSessionOffset,
		arg.UploadOffset,
		arg.S3Parts,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShareID,
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.Description,
		&i.UploadOffset,
		&i.ReplaceFile,
		&i.TempKey,
		&i.S3UploadID,
		&i.S3Parts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
