// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE path = ?1
`

func (q *Queries) DeleteFile(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, path)
	return err
}

const deleteFilesUnder = `-- name: DeleteFilesUnder :exec
DELETE FROM files WHERE path = ?1 OR path LIKE ?2
`

type DeleteFilesUnderParams struct {
	Path     string `json:"path"`
	PathLike string `json:"path_like"`
}

func (q *Queries) DeleteFilesUnder(ctx context.Context, arg DeleteFilesUnderParams) error {
	_, err := q.db.ExecContext(ctx, deleteFilesUnder, arg.Path, arg.PathLike)
	return err
}

const getFile = `-- name: GetFile :one
SELECT path, size, content_type, description, user_id, created_at, updated_at FROM files WHERE path = ?1
`

func (q *Queries) GetFile(ctx context.Context, path string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, path)
	var i File
	err := row.Scan(
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllFilePaths = `-- name: ListAllFilePaths :many
SELECT path FROM files ORDER BY path
`

func (q *Queries) ListAllFilePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllFilePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesUnder = `-- name: ListFilesUnder :many
SELECT path, size, content_type, description, user_id, created_at, updated_at FROM files
WHERE path = ?1 OR path LIKE ?2
ORDER BY path
`

type ListFilesUnderParams struct {
	Path     string `json:"path"`
	PathLike string `json:"path_like"`
}

func (q *Queries) ListFilesUnder(ctx context.Context, arg ListFilesUnderParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesUnder, arg.Path, arg.PathLike)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.Path,
			&i.Size,
			&i.ContentType,
			&i.Description,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileMeta = `-- name: UpdateFileMeta :one
UPDATE files
SET path = ?1,
    size = ?2,
    content_type = ?3,
    description = ?4,
    updated_at = ?5
WHERE path = ?6
RETURNING path, size, content_type, description, user_id, created_at, updated_at
`

type UpdateFileMetaParams struct {
	NewPath     string    `json:"new_path"`
	Size        int64     `json:"size"`
	ContentType string    `json:"content_type"`
	Description string    `json:"description"`
	UpdatedAt   time.Time `json:"updated_at"`
	Path        string    `json:"path"`
}

func (q *Queries) UpdateFileMeta(ctx context.Context, arg UpdateFileMetaParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFileMeta,
		arg.NewPath,
		arg.Size,
		arg.ContentType,
		arg.Description,
		arg.UpdatedAt,
		arg.Path,
	)
	var i File
	err := row.Scan(
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFile = `-- name: UpsertFile :one
INSERT INTO files (path, size, content_type, description, user_id, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT (path) DO UPDATE SET
    size = excluded.size,
    content_type = excluded.content_type,
    description = excluded.description,
    user_id = excluded.user_id,
    updated_at = excluded.updated_at
RETURNING path, size, content_type, description, user_id, created_at, updated_at
`

type UpsertFileParams struct {
	Path        string         `json:"path"`
	Size        int64          `json:"size"`
	ContentType string         `json:"content_type"`
	Description string         `json:"description"`
	UserID      sql.NullString `json:"user_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, upsertFile,
		arg.Path,
		arg.Size,
		arg.ContentType,
		arg.Description,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i File
	err := row.Scan(
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
