// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"database/sql"
	"time"
)

type ApiToken struct {
	TokenHash   string    `json:"token_hash"`
	TokenPrefix string    `json:"token_prefix"`
	UserID      string    `json:"user_id"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type File struct {
	Path        string         `json:"path"`
	Size        int64          `json:"size"`
	ContentType string         `json:"content_type"`
	Description string         `json:"description"`
	UserID      sql.NullString `json:"user_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type PathAcl struct {
	Path          string `json:"path"`
	PrincipalType string `json:"principal_type"`
	PrincipalID   string `json:"principal_id"`
	Allow         int64  `json:"allow"`
	Deny          int64  `json:"deny"`
}

type Session struct {
	ID           string    `json:"id"`
	UserID       string    `json:"user_id"`
	AccessToken  string    `json:"access_token"`
	Expiry       time.Time `json:"expiry"`
	RefreshToken string    `json:"refresh_token"`
	IDToken      string    `json:"id_token"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Share struct {
	ID        string       `json:"id"`
	Path      string       `json:"path"`
	UserID    string       `json:"user_id"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

type UploadSession struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	ShareID     sql.NullString `json:"share_id"`
	Path        string         `json:"path"`
	Size        int64          `json:"size"`
	ContentType string         `json:"content_type"`
	Description string         `json:"description"`
	Offset      int64          `json:"offset"`
	ReplaceFile int64          `json:"replace_file"`
	TempKey     string         `json:"temp_key"`
	S3UploadID  sql.NullString `json:"s3_upload_id"`
	S3Parts     string         `json:"s3_parts"`
	ExpiresAt   time.Time      `json:"expires_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Home      string    `json:"home"`
	Groups    string    `json:"groups"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
