// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"context"
)

type Querier interface {
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateShare(ctx context.Context, arg CreateShareParams) (Share, error)
	DeleteACL(ctx context.Context, arg DeleteACLParams) error
	DeleteACLForPath(ctx context.Context, path string) error
	DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error
	DeleteFile(ctx context.Context, path string) error
	DeleteFilesUnder(ctx context.Context, arg DeleteFilesUnderParams) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionsForUser(ctx context.Context, userID string) error
	DeleteShare(ctx context.Context, id string) error
	DeleteSharesForPath(ctx context.Context, path string) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetFile(ctx context.Context, path string) (File, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetShare(ctx context.Context, id string) (Share, error)
	GetUser(ctx context.Context, id string) (User, error)
	ListACLByPath(ctx context.Context, path string) ([]PathAcl, error)
	ListACLByPaths(ctx context.Context, paths []string) ([]PathAcl, error)
	ListAPITokensByUser(ctx context.Context, userID string) ([]ApiToken, error)
	ListAllACL(ctx context.Context) ([]PathAcl, error)
	ListAllFilePaths(ctx context.Context) ([]string, error)
	ListFilesUnder(ctx context.Context, arg ListFilesUnderParams) ([]File, error)
	ListSharesByPath(ctx context.Context, arg ListSharesByPathParams) ([]Share, error)
	ListSharesByUser(ctx context.Context, userID string) ([]Share, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateFileMeta(ctx context.Context, arg UpdateFileMetaParams) (File, error)
	UpsertACL(ctx context.Context, arg UpsertACLParams) (PathAcl, error)
	UpsertFile(ctx context.Context, arg UpsertFileParams) (File, error)
	UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
