// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package dbq

import (
	"context"
	"database/sql"
	"time"
)

const createUploadSession = `-- name: CreateUploadSession :one
INSERT INTO upload_sessions (
    id, user_id, share_id, path, size, content_type, description, offset, replace_file,
    temp_key, s3_upload_id, s3_parts, expires_at, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9,
    ?10, ?11, ?12, ?13, ?14, ?15
)
RETURNING id, user_id, share_id, path, size, content_type, description, "offset", replace_file, temp_key, s3_upload_id, s3_parts, expires_at, created_at, updated_at
`

type CreateUploadSessionParams struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	ShareID     sql.NullString `json:"share_id"`
	Path        string         `json:"path"`
	Size        int64          `json:"size"`
	ContentType string         `json:"content_type"`
	Description string         `json:"description"`
	Offset      int64          `json:"offset"`
	ReplaceFile int64          `json:"replace_file"`
	TempKey     string         `json:"temp_key"`
	S3UploadID  sql.NullString `json:"s3_upload_id"`
	S3Parts     string         `json:"s3_parts"`
	ExpiresAt   time.Time      `json:"expires_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, createUploadSession,
		arg.ID,
		arg.UserID,
		arg.ShareID,
		arg.Path,
		arg.Size,
		arg.ContentType,
		arg.Description,
		arg.Offset,
		arg.ReplaceFile,
		arg.TempKey,
		arg.S3UploadID,
		arg.S3Parts,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShareID,
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.Description,
		&i.Offset,
		&i.ReplaceFile,
		&i.TempKey,
		&i.S3UploadID,
		&i.S3Parts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredUploadSessions = `-- name: DeleteExpiredUploadSessions :many
DELETE FROM upload_sessions
WHERE expires_at < ?1
RETURNING id, user_id, share_id, path, size, content_type, description, "offset", replace_file, temp_key, s3_upload_id, s3_parts, expires_at, created_at, updated_at
`

func (q *Queries) DeleteExpiredUploadSessions(ctx context.Context, now time.Time) ([]UploadSession, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredUploadSessions, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadSession{}
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShareID,
			&i.Path,
			&i.Size,
			&i.ContentType,
			&i.Description,
			&i.Offset,
			&i.ReplaceFile,
			&i.TempKey,
			&i.S3UploadID,
			&i.S3Parts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUploadSession = `-- name: DeleteUploadSession :exec
DELETE FROM upload_sessions WHERE id = ?1
`

func (q *Queries) DeleteUploadSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUploadSession, id)
	return err
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT id, user_id, share_id, path, size, content_type, description, "offset", replace_file, temp_key, s3_upload_id, s3_parts, expires_at, created_at, updated_at FROM upload_sessions WHERE id = ?1
`

func (q *Queries) GetUploadSession(ctx context.Context, id string) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, getUploadSession, id)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShareID,
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.Description,
		&i.Offset,
		&i.ReplaceFile,
		&i.TempKey,
		&i.S3UploadID,
		&i.S3Parts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUploadSessionOffset = `-- name: UpdateUploadSessionOffset :one
UPDATE upload_sessions
SET offset = ?1,
    s3_parts = ?2,
    updated_at = ?3
WHERE id = ?4
RETURNING id, user_id, share_id, path, size, content_type, description, "offset", replace_file, temp_key, s3_upload_id, s3_parts, expires_at, created_at, updated_at
`

type UpdateUploadSessionOffsetParams struct {
	Offset    int64     `json:"offset"`
	S3Parts   string    `json:"s3_parts"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateUploadSessionOffset(ctx context.Context, arg UpdateUploadSessionOffsetParams) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, updateUploadSessionOffset,
		arg.Offset,
		arg.S3Parts,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShareID,
		&i.Path,
		&i.Size,
		&i.ContentType,
		&i.Description,
		&i.Offset,
		&i.ReplaceFile,
		&i.TempKey,
		&i.S3UploadID,
		&i.S3Parts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
