// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func MoveFile(path string, files string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<form id=\"file-move\" hx-patch=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(path + files))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-target=\"main\" hx-swap=\"outerHTML\" hx-error-target=\"#file-move-error\" hx-error-swap=\"innerHTML\" hx-ext=\"destination-header,accept-html\"><div id=\"form-file-navigation\"><div><input name=\"dir\" value=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(path))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"><div class=\"buttons\"><button id=\"move-button\" type=\"submit\" class=\"btn primary\">")
		if err != nil {
			return err
		}
		var_2 := `Move`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button><button type=\"button\" hx-get=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(path + "?action=files"))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-target=\"#content\" class=\"btn secondary\">")
		if err != nil {
			return err
		}
		var_3 := `Cancel`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button></div></div></div><div id=\"file-move-error\"></div></form>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
