// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func UploadFile(path string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<form id=\"file-upload\" hx-post=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(path))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-encoding=\"multipart/form-data\" hx-push-url=\"true\" hx-target=\"main\" hx-swap=\"outerHTML\" hx-error-target=\"#file-upload-error\" hx-error-swap=\"innerHTML\" hx-ext=\"upload-files,accept-html\" hx-on:reset=\"window.onFilesReset(event)\" hx-on:htmx:xhr:progress=\"window.updateUploadProgress(event)\"><div id=\"form-file-navigation\"><progress id=\"upload-progress\" value=\"0\" max=\"100\"></progress><div><input name=\"dir\" value=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(path))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"><div class=\"buttons\"><button id=\"upload-button\" type=\"submit\" class=\"btn primary\" disabled>")
		if err != nil {
			return err
		}
		var_2 := `Upload`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button><button type=\"button\" hx-get=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(path + "?action=files"))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-target=\"#content\" class=\"btn secondary\">")
		if err != nil {
			return err
		}
		var_3 := `Cancel`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button></div></div></div><div id=\"file-upload-error\"></div><ul id=\"upload-files\"></ul><div class=\"file-upload\"><input type=\"file\" id=\"files\" name=\"files\" multiple hidden hx-on:change=\"window.onFilesChange(event)\"><label for=\"files\"><div id=\"upload-icon\" class=\"icon\"></div> ")
		if err != nil {
			return err
		}
		var_4 := `Choose files or drop here.`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label></div></form>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
