//go:build ignore

// gen_db_bridge runs after sqlc generate:
//  1. copies model/param structs from sqlite into database/dbtypes
//  2. re-exports them from package database
//  3. replaces per-engine copies with type aliases to dbtypes
//  4. emits a shared database.Querier interface
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/imports"
)

const (
	modulePath   = "github.com/topi314/godrive"
	dbtypesPath  = modulePath + "/server/database/dbtypes"
	sqliteDir    = "server/database/sqlite"
	postgresDir  = "server/database/postgres"
	databaseDir  = "server/database"
	dbtypesDir   = "server/database/dbtypes"
	generatedHdr = "// Code generated by tools/gen_db_bridge.go; DO NOT EDIT.\n\n"
)

func main() {
	fset := token.NewFileSet()
	types := collectSharedTypes(fset, sqliteDir)
	methods := collectQuerierMethods(mustParse(fset, filepath.Join(sqliteDir, "querier.go")))
	names := typeNames(types)

	must(os.MkdirAll(dbtypesDir, 0o755))
	writeGo(filepath.Join(dbtypesDir, "types_gen.go"), genPackage("dbtypes", typesImports(fset, types), renderTypes(fset, types)))
	writeGo(filepath.Join(databaseDir, "types_gen.go"), genAliases("database", "dbtypes", dbtypesPath, names))
	writeGo(filepath.Join(databaseDir, "querier_gen.go"), genQuerier(methods))

	for _, dir := range []string{sqliteDir, postgresDir} {
		stripSharedTypes(fset, dir, names)
		writeGo(filepath.Join(dir, "aliases_gen.go"), genAliases(filepath.Base(dir), "dbtypes", dbtypesPath, names))
		_ = os.Remove(filepath.Join(dir, "models.go"))
	}

	fmt.Printf("shared %d types via dbtypes; aliased into sqlite + postgres\n", len(types))
}

type sharedType struct {
	name string
	spec *ast.TypeSpec
}

type method struct {
	name    string
	params  []field
	results []string
}

type field struct {
	name, typ string
}

func collectSharedTypes(fset *token.FileSet, dir string) []sharedType {
	seen := map[string]bool{}
	var out []sharedType
	for _, path := range mustGlob(filepath.Join(dir, "*.go")) {
		if filepath.Base(path) == "aliases_gen.go" {
			continue
		}
		f := mustParse(fset, path)
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				if _, ok := ts.Type.(*ast.StructType); !ok || !isSharedType(ts.Name.Name) || seen[ts.Name.Name] {
					continue
				}
				seen[ts.Name.Name] = true
				out = append(out, sharedType{name: ts.Name.Name, spec: ts})
			}
		}
	}
	if len(out) == 0 {
		fail("no model structs in %s; run sqlc generate first", dir)
	}
	return out
}

func isSharedType(name string) bool {
	return name != "Queries" && name != "DBTX"
}

func typeNames(types []sharedType) []string {
	names := make([]string, len(types))
	for i, t := range types {
		names[i] = t.name
	}
	return names
}

func collectQuerierMethods(f *ast.File) []method {
	var methods []method
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != "Querier" {
			return true
		}
		it, ok := ts.Type.(*ast.InterfaceType)
		if !ok {
			return false
		}
		for _, meth := range it.Methods.List {
			ft := meth.Type.(*ast.FuncType)
			m := method{name: meth.Names[0].Name}
			for i, p := range ft.Params.List {
				name := fmt.Sprintf("a%d", i)
				if len(p.Names) > 0 {
					name = p.Names[0].Name
				}
				m.params = append(m.params, field{name: name, typ: exprString(p.Type)})
			}
			if ft.Results != nil {
				for _, r := range ft.Results.List {
					m.results = append(m.results, exprString(r.Type))
				}
			}
			methods = append(methods, m)
		}
		return false
	})
	return methods
}

func exprString(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return exprString(t.X) + "." + t.Sel.Name
	case *ast.ArrayType:
		return "[]" + exprString(t.Elt)
	case *ast.StarExpr:
		return "*" + exprString(t.X)
	case *ast.InterfaceType:
		return "any"
	default:
		fail("unsupported expr %T", e)
		return ""
	}
}

func typesImports(fset *token.FileSet, types []sharedType) []string {
	needSQL, needTime := false, false
	for _, t := range types {
		var b bytes.Buffer
		_ = format.Node(&b, fset, t.spec)
		s := b.String()
		needSQL = needSQL || strings.Contains(s, "sql.")
		needTime = needTime || strings.Contains(s, "time.")
	}
	var imports []string
	if needSQL {
		imports = append(imports, `"database/sql"`)
	}
	if needTime {
		imports = append(imports, `"time"`)
	}
	return imports
}

func renderTypes(fset *token.FileSet, types []sharedType) string {
	var b strings.Builder
	for _, t := range types {
		b.WriteString("type ")
		if err := format.Node(&b, fset, t.spec); err != nil {
			fail("render %s: %v", t.name, err)
		}
		b.WriteString("\n\n")
	}
	return b.String()
}

func genPackage(pkg string, imports []string, body string) string {
	var b strings.Builder
	b.WriteString(generatedHdr)
	b.WriteString("package ")
	b.WriteString(pkg)
	b.WriteString("\n\n")
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString("\t")
			b.WriteString(imp)
			b.WriteString("\n")
		}
		b.WriteString(")\n\n")
	}
	b.WriteString(body)
	return b.String()
}

func genAliases(pkg, alias, importPath string, names []string) string {
	var b strings.Builder
	b.WriteString(generatedHdr)
	b.WriteString("package ")
	b.WriteString(pkg)
	b.WriteString("\n\n")
	b.WriteString("import \"")
	b.WriteString(importPath)
	b.WriteString("\"\n\n")
	for _, name := range names {
		fmt.Fprintf(&b, "type %s = %s.%s\n", name, alias, name)
	}
	return b.String()
}

func genQuerier(methods []method) string {
	needTime := false
	for _, m := range methods {
		for _, p := range m.params {
			needTime = needTime || strings.Contains(p.typ, "time.")
		}
		for _, r := range m.results {
			needTime = needTime || strings.Contains(r, "time.")
		}
	}

	imports := []string{`"context"`}
	if needTime {
		imports = append(imports, `"time"`)
	}

	var body strings.Builder
	body.WriteString("// Querier is the shared database API implemented by sqlite and postgres.\n")
	body.WriteString("type Querier interface {\n")
	for _, m := range methods {
		body.WriteString("\t")
		body.WriteString(m.name)
		body.WriteByte('(')
		for i, p := range m.params {
			if i > 0 {
				body.WriteString(", ")
			}
			body.WriteString(p.name)
			body.WriteByte(' ')
			body.WriteString(p.typ)
		}
		body.WriteByte(')')
		switch len(m.results) {
		case 0:
		case 1:
			body.WriteByte(' ')
			body.WriteString(m.results[0])
		default:
			body.WriteString(" (")
			body.WriteString(strings.Join(m.results, ", "))
			body.WriteByte(')')
		}
		body.WriteByte('\n')
	}
	body.WriteString("}\n")
	return genPackage("database", imports, body.String())
}

func stripSharedTypes(fset *token.FileSet, dir string, names []string) {
	drop := map[string]bool{}
	for _, n := range names {
		drop[n] = true
	}
	for _, path := range mustGlob(filepath.Join(dir, "*.go")) {
		base := filepath.Base(path)
		if base == "aliases_gen.go" || base == "models.go" {
			continue
		}
		src := mustRead(path)
		f, err := parser.ParseFile(fset, path, src, parser.ParseComments)
		if err != nil {
			fail("parse %s: %v", path, err)
		}
		changed := false
		keep := f.Decls[:0]
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				keep = append(keep, decl)
				continue
			}
			specs := gd.Specs[:0]
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				if drop[ts.Name.Name] {
					changed = true
					continue
				}
				specs = append(specs, spec)
			}
			if len(specs) == 0 {
				changed = true
				continue
			}
			gd.Specs = specs
			keep = append(keep, gd)
		}
		if !changed {
			continue
		}
		f.Decls = keep
		var buf bytes.Buffer
		if err := format.Node(&buf, fset, f); err != nil {
			fail("format %s: %v", path, err)
		}
		out, err := imports.Process(path, buf.Bytes(), nil)
		if err != nil {
			fail("imports %s: %v", path, err)
		}
		mustWrite(path, out)
	}
}

func writeGo(path, src string) {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		fail("format %s: %v\n%s", path, err, src)
	}
	mustWrite(path, formatted)
}

func mustGlob(pattern string) []string {
	matches, err := filepath.Glob(pattern)
	if err != nil {
		fail("glob %s: %v", pattern, err)
	}
	return matches
}

func mustParse(fset *token.FileSet, path string) *ast.File {
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		fail("parse %s: %v", path, err)
	}
	return f
}

func mustRead(path string) []byte {
	b, err := os.ReadFile(path)
	if err != nil {
		fail("read %s: %v", path, err)
	}
	return b
}

func mustWrite(path string, b []byte) {
	if err := os.WriteFile(path, b, 0o644); err != nil {
		fail("write %s: %v", path, err)
	}
}

func must(err error) {
	if err != nil {
		fail("%v", err)
	}
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
